import { memo, useState, useEffect } from 'react'

const HeroSection = memo(function HeroSection() {
	const [displayText, setDisplayText] = useState('')
	const [wordIndex, setWordIndex] = useState(0)
	const [isDeleting, setIsDeleting] = useState(false)

	useEffect(() => {
		const words = ['receipts', 'lists']
		const currentWord = words[wordIndex]
		const typingSpeed = isDeleting ? 50 : 100 // Faster deletion
		const pauseDuration = 2000 // 2 second pause when word is complete

		const timeout = setTimeout(() => {
			if (!isDeleting) {
				// Typing forward
				if (displayText.length < currentWord.length) {
					setDisplayText(currentWord.substring(0, displayText.length + 1))
				} else {
					// Word is complete, pause then start deleting
					setTimeout(() => setIsDeleting(true), pauseDuration)
				}
			} else {
				// Deleting backward
				if (displayText.length > 0) {
					setDisplayText(displayText.substring(0, displayText.length - 1))
				} else {
					// Finished deleting, move to next word
					setIsDeleting(false)
					setWordIndex((wordIndex + 1) % words.length)
				}
			}
		}, typingSpeed)

		return () => clearTimeout(timeout)
	}, [displayText, wordIndex, isDeleting])

	return (
		<section id="home" className="mt-8 mb-10 md:mt-11 md:mb-14">
			<div className="max-w-4xl mx-auto text-center px-4">
				{/* Hero badge */}
				<div className="relative inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/40 backdrop-blur-2xl border border-white/15 shadow-[0_8px_32px_rgba(0,0,0,0.06),inset_0_1px_0_rgba(255,255,255,0.8)] mb-5 before:absolute before:inset-0 before:rounded-full before:bg-gradient-to-b before:from-white/50 before:to-white/0 before:opacity-60 before:pointer-events-none">
					<span className="w-1.5 h-1.5 rounded-full bg-emerald-500 shadow-[0_0_0_3px_rgba(16,185,129,0.15)]" />
					<span className="text-[11px] sm:text-[12px] font-medium text-gray-900">
						1K+ meal plans generated by 100+ home cooks
					</span>
				</div>

				{/* Headline */}
				<h1 className="heading text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight text-gray-900 mb-4 md:mb-5">
					Turn grocery{' '}
					<span className="italic px-2 sm:px-3 py-0.5 sm:py-1 rounded-md bg-[#E9D5FF] inline-block whitespace-nowrap">
						{displayText}
						<span className="animate-pulse">|</span>
					</span>
					<br />
					into meal plans
				</h1>

				{/* Subcopy */}
				<p className="text-sm sm:text-base text-gray-600 mb-6 md:mb-8 max-w-2xl mx-auto">
					Upload a grocery receipt or list and get a personalized, diet‑friendly plan that uses only what you bought.
				</p>

				{/* CTAs */}
				<div className="flex flex-wrap items-center justify-center gap-3 mb-6 md:mb-8">
					<button className="inline-flex items-center justify-center px-6 md:px-7 py-2.5 md:py-3 rounded-full text-sm font-semibold bg-[#C6A0F6] text-gray-900 shadow-md hover:bg-[#b58df5] transition-colors duration-200">
						Try Edible for Free
					</button>
					<button className="inline-flex items-center justify-center px-5 md:px-6 py-2.5 md:py-3 rounded-full text-sm font-semibold border border-gray-300 bg-white/80 text-gray-800 hover:bg-gray-50 transition-colors duration-200">
						Watch demo (coming soon)
					</button>
				</div>

				{/* Social proof */}
				<div className="flex flex-col items-center gap-2 text-xs md:text-sm text-gray-500">
					<div className="flex items-center gap-2">
						<div className="flex -space-x-2">
							<div className="w-7 h-7 rounded-full bg-purple-200 border border-white" />
							<div className="w-7 h-7 rounded-full bg-emerald-200 border border-white" />
							<div className="w-7 h-7 rounded-full bg-sky-200 border border-white" />
						</div>
						<span className="font-semibold text-gray-800">12k+</span>
						<span className="text-gray-500">meal plans generated for busy home cooks</span>
					</div>
				</div>
			</div>
		</section>
	)
})

export default HeroSection
